<body style="background-color:FFFF33;">
<h1 style="text-align:left; font-family:serif; font-size:200%">Importing the Libraries</h1>

In [1]:
import numpy as np
import pandas as pd

import scipy.stats as stats
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

<body style="background-color:FFFF33;">
<h1 style="text-align:left; font-family:serif; font-size:200%">Importing the Data-Set</h1>

In [2]:
df = pd.read_excel('Procrastination self Assessment form.xls')
df.head()

,Timestamp,Age,I often watch movies night,I go to bed early if I must get up early in the morning,"If it is time to turn off the lights at night, I overthink what I read/watch before sleeping",I have a regular bedtime which I keep to,I easily stop with my activities when it is time to go to bed,I get inspired by my friend circle work punctuality,I postpone my work due to sudden/unexpected plans with my circle,I get discouraged by my higher officials/Family,I get demotivated on comparing myself with others and postpone my works,I get upset easily and delay my work if I have negative argument with my colleague,I find it hard to concentrate and get focused on a task,I leave difficult tasks to the last minute and complete them under pressure,I tend to delay implementing plans I have agreed,I miss deadlines because less important tasks have gotten in the way,I spend time worrying about making mistakes before starting on a task
0,2022/03/14 10:32:55 pm GMT+5:30,18-24,3,2,2,1,1,1,4,2,1,1,4,5,4,3,4.0
1,2022/03/14 10:35:59 pm GMT+5:30,18-24,5,5,2,4,4,5,4,2,2,3,4,3,4,2,3.0
2,2022/03/14 10:37:54 pm GMT+5:30,18-24,3,2,1,4,3,5,5,2,3,2,3,3,3,2,2.0
3,2022/03/14 10:39:02 pm GMT+5:30,18-24,4,2,1,2,2,4,3,2,2,1,5,2,2,1,3.0
4,2022/03/14 10:47:09 pm GMT+5:30,18-24,4,3,4,3,3,5,4,4,4,3,4,5,3,3,3.0

In [3]:
print("Number of response collected : ",len(df))

Number of response collected :  88

<body style="background-color:FFFF33;">
    <h1 style="text-align:left; font-family:serif; font-size:200%">F-Test</h1>

In [4]:
def f_test(x, y):
    x = np.array(x)
    y = np.array(y)
    f = np.var(x, ddof=1)/np.var(y, ddof=1) #calculate F test statistic 
    dfn = x.size-1                    #define degrees of freedom numerator 
    dfd = y.size-1 #define degrees of freedom denominator 
    p = 1-stats.f.cdf(f, dfn, dfd) #find p-value of F test statistic 
    return f, p

<body style="background-color:FFFF33;">
 <h1 style="text-align:center; font-family:serif; font-size:300%">Dealing with objective-1</h1>

In [5]:
question_1 = df.iloc[:,2:6]
question_1.head()

,I often watch movies night,I go to bed early if I must get up early in the morning,"If it is time to turn off the lights at night, I overthink what I read/watch before sleeping",I have a regular bedtime which I keep to
0,3,2,2,1
1,5,5,2,4
2,3,2,1,4
3,4,2,1,2
4,4,3,4,3

In [6]:
question_1['index'] = question_1.index
question_1.head()

,I often watch movies night,I go to bed early if I must get up early in the morning,"If it is time to turn off the lights at night, I overthink what I read/watch before sleeping",I have a regular bedtime which I keep to,index
0,3,2,2,1,0
1,5,5,2,4,1
2,3,2,1,4,2
3,4,2,1,2,3
4,4,3,4,3,4

In [7]:
print("Answers Options :  ",len(question_1.columns))

Answers Options :   5

<body style="background-color:FFFF33;">
<h1 style="text-align:left; font-family:serif; font-size:200%">Dividing into Activists and Non Activists</h1>

In [8]:
activists = question_1[(question_1["I often watch movies night"] > 4) |
                                   (question_1["If it is time to turn off the lights at night, I overthink what I read/watch before sleeping"] > 3)]

print(len(activists))
activists.head()

40

,I often watch movies night,I go to bed early if I must get up early in the morning,"If it is time to turn off the lights at night, I overthink what I read/watch before sleeping",I have a regular bedtime which I keep to,index
1,5,5,2,4,1
4,4,3,4,3,4
5,5,5,4,1,5
6,5,5,4,3,6
7,5,2,3,2,7

In [9]:
non_activists = question_1[question_1.index.isin(activists.index) == False]

print(len(non_activists))
non_activists.head()

48

,I often watch movies night,I go to bed early if I must get up early in the morning,"If it is time to turn off the lights at night, I overthink what I read/watch before sleeping",I have a regular bedtime which I keep to,index
0,3,2,2,1,0
2,3,2,1,4,2
3,4,2,1,2,3
9,4,4,3,3,9
10,1,3,3,3,10

In [10]:
activists.drop('index', axis='columns', inplace=True)
activists.loc[:,'Row_Total']        = activists.sum(numeric_only=True, axis=1)

non_activists.drop('index', axis='columns', inplace=True)
non_activists.loc[:,'Row_Total'] = non_activists.sum(numeric_only=True, axis=1)

<body style="background-color:FFFF33;">
    <h1 style="text-align:left; font-family:serif; font-size:200%">Perform F-Test</h1>

In [11]:
variable_1 = activists.sample(n=30)['Row_Total']
variable_2 = non_activists.sample(n=30)['Row_Total']

In [12]:
print(variable_1)

35    18
36    13
58    11
27    14
6     17
43    11
82    18
11    13
53    11
39    15
4     14
34    14
1     16
15    20
78    11
54    17
63    15
21    10
79    16
72    15
83    15
74    16
47    15
66    14
30     9
81    19
14    13
18    14
13    14
87    16
Name: Row_Total, dtype: int64

In [13]:
print(variable_2)

57     6
49     5
71     5
40    10
38    15
41    13
28    14
77    12
62     8
25    10
26    12
9     14
0      8
42     8
52     7
55     8
48     4
75    13
65    13
50     6
20    13
69     8
59    10
73    11
23    10
46    10
56    10
16    12
29    13
31    10
Name: Row_Total, dtype: int64

In [14]:
f_value, p_value = f_test(variable_1, variable_2)

print(f_value)
print(p_value)

0.7846232179226068
0.7410874182720666

In [15]:
if p_value < 0.05:   
    print("Rejecting Null Hypothesis (i.e) Accepting Alternate Hypothesis")
else:
    print("Accepting Null Hypothesis (i.e) Rejecting Alternate Hypothesis")

Accepting Null Hypothesis (i.e) Rejecting Alternate Hypothesis

<body style="background-color:FFFF33;">
    <h1 style="text-align:center; font-family:serif; font-size:300%">Dealing with Objective-2</h1>

In [16]:
question_2 = df.iloc[:,7:12]

question_2.head()

,I get inspired by my friend circle work punctuality,I postpone my work due to sudden/unexpected plans with my circle,I get discouraged by my higher officials/Family,I get demotivated on comparing myself with others and postpone my works,I get upset easily and delay my work if I have negative argument with my colleague
0,1,4,2,1,1
1,5,4,2,2,3
2,5,5,2,3,2
3,4,3,2,2,1
4,5,4,4,4,3

In [17]:
question_2['index'] = question_2.index
question_2.head()

,I get inspired by my friend circle work punctuality,I postpone my work due to sudden/unexpected plans with my circle,I get discouraged by my higher officials/Family,I get demotivated on comparing myself with others and postpone my works,I get upset easily and delay my work if I have negative argument with my colleague,index
0,1,4,2,1,1,0
1,5,4,2,2,3,1
2,5,5,2,3,2,2
3,4,3,2,2,1,3
4,5,4,4,4,3,4

In [18]:
print("Answers Options :  ",len(question_2.columns))

Answers Options :   6

<body style="background-color:FFFF33;">
<h1 style="text-align:left; font-family:serif; font-size:200%">Dividing into People Around Us are Procastinating / Not</h1>

In [19]:
ar_procastinated = question_2[
                                    (question_2['I get inspired by my friend circle work punctuality'] > 4) | 
                                    (question_2['I postpone my work due to sudden/unexpected plans with my circle'] > 3) |
                                    (question_2['I get demotivated on comparing myself with others and postpone my works'] > 4)
                            ]

print(len(ar_procastinated))
ar_procastinated.head()

56

,I get inspired by my friend circle work punctuality,I postpone my work due to sudden/unexpected plans with my circle,I get discouraged by my higher officials/Family,I get demotivated on comparing myself with others and postpone my works,I get upset easily and delay my work if I have negative argument with my colleague,index
0,1,4,2,1,1,0
1,5,4,2,2,3,1
2,5,5,2,3,2,2
4,5,4,4,4,3,4
5,4,5,3,3,4,5

In [20]:
non_ar_procastinated = question_2[question_2.index.isin(ar_procastinated.index) == False]

print(len(non_ar_procastinated))
non_ar_procastinated.head()

32

,I get inspired by my friend circle work punctuality,I postpone my work due to sudden/unexpected plans with my circle,I get discouraged by my higher officials/Family,I get demotivated on comparing myself with others and postpone my works,I get upset easily and delay my work if I have negative argument with my colleague,index
3,4,3,2,2,1,3
12,4,3,2,2,2,12
19,3,3,1,1,4,19
20,4,3,4,4,3,20
21,2,3,3,3,4,21

In [21]:
ar_procastinated.drop('index', axis='columns', inplace=True)
ar_procastinated.loc[:,'Row_Total']        = ar_procastinated.sum(numeric_only=True, axis=1)

non_ar_procastinated.drop('index', axis='columns', inplace=True)
non_ar_procastinated.loc[:,'Row_Total'] = non_ar_procastinated.sum(numeric_only=True, axis=1)

In [22]:
variable_1 = ar_procastinated.sample(n=30)['Row_Total']
variable_2 = non_ar_procastinated.sample(n=30)['Row_Total']

In [23]:
print(variable_1)

13    19
72    21
76    16
44    20
17    19
6     21
28    14
5     19
16    19
86    14
15    16
18     9
45    16
65    16
7     15
53    18
80    21
2     17
75    10
70    14
23    13
54    17
66    13
9     15
71    16
55    13
35    18
81    22
78    25
85    14
Name: Row_Total, dtype: int64

In [24]:
print(variable_2)

37    14
49     9
29    11
41     5
67     7
46    13
50    10
60    10
20    18
83    17
51    15
58    16
59    14
48     5
12    13
63     9
22    14
21    15
64    13
30    11
36    18
62    12
3     12
84    13
61    13
69     9
82    11
52    11
19    12
57    15
Name: Row_Total, dtype: int64

<body style="background-color:FFFF33;">
    <h1 style="text-align:left; font-family:serif; font-size:200%">Perform F-Test</h1>

In [25]:
f_value, p_value = f_test(variable_1, variable_2)

print("f-value : {}".format(f_value),end = ' ')
print("and p-value : ",p_value)

f-value : 1.165007857517025 and p-value :  0.3418178389626032

In [26]:
if p_value < 0.05:   
    print("Rejecting Null Hypothesis (i.e) Accepting Alternate Hypothesis")
else:
    print("Accepting Null Hypothesis (i.e) Rejecting Alternate Hypothesis")

Accepting Null Hypothesis (i.e) Rejecting Alternate Hypothesis

<body style="background-color:FFFF33;">
    <h1 style="text-align:center; font-family:serif; font-size:300%">Dealing with Question-3</h1>

In [27]:
question_3 = df.iloc[:,12:17]

question_3.head()

,I find it hard to concentrate and get focused on a task,I leave difficult tasks to the last minute and complete them under pressure,I tend to delay implementing plans I have agreed,I miss deadlines because less important tasks have gotten in the way,I spend time worrying about making mistakes before starting on a task
0,4,5,4,3,4.0
1,4,3,4,2,3.0
2,3,3,3,2,2.0
3,5,2,2,1,3.0
4,4,5,3,3,3.0

In [28]:
question_3['index'] = question_3.index
question_3.head()

,I find it hard to concentrate and get focused on a task,I leave difficult tasks to the last minute and complete them under pressure,I tend to delay implementing plans I have agreed,I miss deadlines because less important tasks have gotten in the way,I spend time worrying about making mistakes before starting on a task,index
0,4,5,4,3,4.0,0
1,4,3,4,2,3.0,1
2,3,3,3,2,2.0,2
3,5,2,2,1,3.0,3
4,4,5,3,3,3.0,4

In [29]:
print("Answers Options :  ",len(question_3.columns))

Answers Options :   6

In [30]:
question_3.loc[:,'Row_Total']    = question_3.sum(numeric_only=True, axis=1)

question_3.tail()

,I find it hard to concentrate and get focused on a task,I leave difficult tasks to the last minute and complete them under pressure,I tend to delay implementing plans I have agreed,I miss deadlines because less important tasks have gotten in the way,I spend time worrying about making mistakes before starting on a task,index,Row_Total
83,3,3,3,2,3.0,83,97.0
84,2,3,3,3,3.0,84,98.0
85,2,2,2,1,1.0,85,93.0
86,2,2,2,2,1.0,86,95.0
87,4,3,2,4,4.0,87,104.0

<body style="background-color:FFFF33;">
<h1 style="text-align:left; font-family:serif; font-size:200%">To investigate if a break in our plan schedule make us procrastinate in our work/activities ?</h1>

In [31]:
break_plan_procastinated = question_3[ (question_3['I find it hard to concentrate and get focused on a task'] > 3) |
                                                              (question_3['I miss deadlines because less important tasks have gotten in the way'] > 2) |
                                                              (question_3['I spend time worrying about making mistakes before starting on a task'] > 3) ] 
            
print(len(break_plan_procastinated))
break_plan_procastinated.head()

61

,I find it hard to concentrate and get focused on a task,I leave difficult tasks to the last minute and complete them under pressure,I tend to delay implementing plans I have agreed,I miss deadlines because less important tasks have gotten in the way,I spend time worrying about making mistakes before starting on a task,index,Row_Total
0,4,5,4,3,4.0,0,20.0
1,4,3,4,2,3.0,1,17.0
3,5,2,2,1,3.0,3,16.0
4,4,5,3,3,3.0,4,22.0
5,4,3,3,4,3.0,5,22.0

In [32]:
non_break_plan_procastinated = question_3[question_3.index.isin(break_plan_procastinated.index) == False]

print(len(non_break_plan_procastinated))
non_break_plan_procastinated.head()

27

,I find it hard to concentrate and get focused on a task,I leave difficult tasks to the last minute and complete them under pressure,I tend to delay implementing plans I have agreed,I miss deadlines because less important tasks have gotten in the way,I spend time worrying about making mistakes before starting on a task,index,Row_Total
2,3,3,3,2,2.0,2,15.0
16,3,2,3,1,3.0,16,28.0
18,2,1,1,1,1.0,18,24.0
23,3,1,2,1,2.0,23,32.0
26,3,1,1,1,1.0,26,33.0

In [33]:
break_plan_procastinated.drop('index', axis='columns', inplace=True)
break_plan_procastinated.loc[:,'Row_Total']        = break_plan_procastinated.sum(numeric_only=True, axis=1)

non_break_plan_procastinated.drop('index', axis='columns', inplace=True)
non_break_plan_procastinated.loc[:,'Row_Total'] = non_break_plan_procastinated.sum(numeric_only=True, axis=1)

In [34]:
variable_1 = break_plan_procastinated.sample(n=25)['Row_Total']
variable_2 = non_break_plan_procastinated.sample(n=25)['Row_Total']

In [35]:
print(variable_1)

21     51.0
82    110.0
72    120.0
34     72.0
59     95.0
44     94.0
78    124.0
74    102.0
12     46.0
79    117.0
67    103.0
1      33.0
64    102.0
46     72.0
28     58.0
55     87.0
5      39.0
7      41.0
30     60.0
38     74.0
49     79.0
14     56.0
15     39.0
27     59.0
60     88.0
Name: Row_Total, dtype: float64

<body style="background-color:FFFF33;">
    <h1 style="text-align:left; font-family:serif; font-size:200%">Perform F-Test</h1>

In [36]:
f_value, p_value = f_test(variable_1, variable_2)

print("f-value : {}".format(f_value),end = ' ')
print("and p-value : ",p_value)

f-value : 1.2928642384105962 and p-value :  0.26703192351434213

In [37]:
if p_value < 0.05:   
    print("Rejecting Null Hypothesis (i.e) Accepting Alternate Hypothesis")
else:
    print("Accepting Null Hypothesis (i.e) Rejecting Alternate Hypothesis")

Accepting Null Hypothesis (i.e) Rejecting Alternate Hypothesis